name: Pre-commit

on:
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up uv venv and install pre-commit and test deps
        run: |
          uv venv
          # Install pre-commit and test dependencies to allow running tests in pre-commit job
          uv pip install pre-commit pytest pytest-cov

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-precommit-

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest -q --disable-warnings -q
